steps:
#  # Build the container image
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '--platform', 'linux/amd64', '--tag', '${_IMAGE_NAME}', '--cache-from', '${_IMAGE_NAME}', '.']
#
#  # Push the container image to Container Registry
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', '${_IMAGE_NAME}']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'instance-1',
      '--image', '${_IMAGE_NAME}',
      '--region', '${_REGION}',
      '--allow-unauthenticated',
      '--add-cloudsql-instances', '${_MYSQL_INSTANCE}',

      # Secret Manager

      '--set-env-vars=COOKIE_SECRET=secret',
      '--set-env-vars=COOKIE_DOMAIN=localhost',

      '--update-secrets=FACEBOOK_AUTH_ID=FACEBOOK_AUTH_ID:latest',
      '--update-secrets=FACEBOOK_AUTH_SECRET=FACEBOOK_AUTH_SECRET:latest',

      '--update-secrets=GITHUB_AUTH_ID=GITHUB_AUTH_ID:latest',
      '--update-secrets=GITHUB_AUTH_SECRET=GITHUB_AUTH_SECRET:latest',

      '--update-secrets=GOOGLE_AUTH_ID=GOOGLE_AUTH_ID:latest',
      '--update-secrets=GOOGLE_AUTH_SECRET=GOOGLE_AUTH_SECRET:latest',

      '--update-secrets=JWT_SECRET=JWT_SECRET:latest',
      '--update-secrets=JWT_ISSUER=JWT_ISSUER:latest',
      '--update-secrets=JWT_AUDIENCE=JWT_AUDIENCE:latest',
      '--update-secrets=JWT_ACCESS_TTL=JWT_ACCESS_TTL:latest',
      '--update-secrets=JWT_REFRESH_TTL=JWT_REFRESH_TTL:latest',

      '--update-secrets=SWAGGER_STATS_USER=SWAGGER_STATS_USER:latest',
      '--update-secrets=SWAGGER_STATS_PASSWORD=SWAGGER_STATS_PASSWORD:latest',

      '--set-env-vars=MAILER_HOST=smtp.ethereal.email',
      '--set-env-vars=MAILER_PORT=587',
      '--set-env-vars=MAILER_USER=kennith.kiehn@ethereal.email',
      '--set-env-vars=MAILER_PASSWORD=NUw4BaaGKYuRttP8vB',

      '--update-secrets=MYSQL_DATABASE_URL=MYSQL_DATABASE_URL:latest',
    ]

substitutions:
  _REGION: 'asia-east1'
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/draft-api-gcp'
  _MYSQL_INSTANCE: '${PROJECT_ID}:us-central1:instance-db'

options:
  dynamicSubstitutions: true
