steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '--target', '${_TARGET}', '--tag', '${_IMAGE_NAME}', '--cache-from', '${_IMAGE_NAME}', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

  # Create job to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'jobs', 'deploy', '${_TARGET}',
      '--image', '${_IMAGE_NAME}',
      '--region', '${_REGION}',
      '--project', '${PROJECT_ID}',
      '--max-retries', '1',
      '--set-cloudsql-instances', '${_MYSQL_INSTANCE}',

      # APP ENV

      '--set-secrets=APP_ORIGIN=APP_ORIGIN:latest',
      '--set-secrets=APP_ENV=APP_ENV:latest',

      # MySQL

      '--set-secrets=MYSQL_DATABASE_URL=MYSQL_DATABASE_URL:latest'
    ]

substitutions:
  _REGION: 'asia-east1'
  _TARGET: 'migrate'
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/draft-api-gcp-${_TARGET}'
  _MYSQL_INSTANCE: '${PROJECT_ID}:us-central1:instance-db'

options:
  dynamicSubstitutions: true
